# Generated by Django 4.0.5 on 2022-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=250)),
                ('team_name', models.CharField(max_length=250)),
                ('bowlers', models.CharField(max_length=500)),
                ('events', models.CharField(max_length=500)),
            ],
        ),
    ]
