# Generated by Django 4.0.5 on 2022-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingstat', '0003_eventdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='team_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='team_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
